spring:
  liquibase:
    enabled: true
#    change-log: classpath:db/changelog/db.changelog-master.yaml

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/wine_store
    username: postgres
    password: "8066"


